services:
  - type: web
    name: agenda-academica-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: FIREBASE_CONFIG
        sync: false
